server:
    port: 7878
    servlet:
        context-path: /context-path
spring:
    application:
        name: demo
    datasource:
        driverClassName: org.h2.Driver
        password: test
        url: jdbc:h2:mem:testdb
        username: test
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: =org.hibernate.dialect.H2Dialect
